### ISSUE TITLE
HTML dump of Duo auth page

### ISSUE THREAD

**Issue by mizlan** [AvikRao/duo-extension#3]
Hi, I'm also writing my own Duo extension: https://github.com/mizlan/AutofillDuo

I was curious if you could provide an HTML dump of the auth prompt page, since my UI seems to be quite different than the querySelectors I see in your code.

**Comment by mizlan** [comment]
Never mind, that won't be too useful now. Turns out its Universal Prompt vs Traditional Prompt:
https://duo.com/docs/protecting-applications

My institution uses Universal Prompt, yours seems to use Traditional. Would you mind elaborating on how my `content.js` could be adapted for the Traditional Prompt, which I'm suspecting might be an iframe?

**Comment by mizlan** [comment]
Oop, better link:

https://help.duo.com/s/article/7118?language=en_US

**Comment by avikrao** [comment]
Extension supports both prompts as of 285804e
