### ISSUE TITLE
[Defect] Scanning QR problem

### ISSUE THREAD

**Issue by MatanelP** [AvikRao/duo-extension#5]
Hello! 

First of all, I absolutely love this extension and it saves me a lot of time.

Unfortunately, I migrated to a new machine and when I tried to relink my Duo account using the build QR scan, I failed every time.

I think Duo updated their front and maybe that is causing the issue.

please add support so that it will work now as well.

![image](https://github.com/AvikRao/duo-extension/assets/75391764/19ec8c39-46f4-40b8-a4c0-e612ef5f84e3)
![image](https://github.com/AvikRao/duo-extension/assets/75391764/5aad4c5d-8618-4a64-b721-2f8cda2b5a6c)

**Comment by dmorla** [comment]
Hi, I have the same issue. I can't relink my Duo Accont. They have any solution? Thanks

**Comment by navaizrael** [comment]
Hello, I'm having the same issue. I'm hoping this will be fixed soon. Thanks

**Comment by avikrao** [comment]
Hey folks (@MatanelP @navaizrael @dmgralla), I'm really sorry about the delay -- have been super busy with my first job this summer.
This is fixed as of 85cea3bca8a0ad862d1ad6a05cd7a683c9f8a315 and is live in version 2.0.1 of the extension on both Firefox AMO and Chrome Web Store. Thanks for your patience 🙏
